{{- range $name, $values := dict "api" .Values.api "cron" .Values.cron "lcg" .Values.liveControllerGateway "webui" .Values.webUi -}}
{{- if $values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "openshock.fullname" $ }}-{{ $name }}'
  labels:
    {{- include "openshock.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openshock.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
---
{{- end }}
{{- end }}
